version: '3.1'
services:
  db-mysql:
    image: mysql
    container_name: db-mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: 111111
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - /root/mysql:/var/lib/mysql