spring:
  datasource:
    url: jdbc:mysql://localhost/issuetracker?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 111111
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update